#!/usr/bin/env bash
# Configure your domain zone so that the subdomain
#  www points to your load-balancer IP (lb-01).

display_info() {
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk 'NR==2 { print "The subdomain $2 is a record and points to " $5 }'
}

display_default_subdomains() {
    local domain="$1"
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"; do
        display_info "$domain" "$subdomain"
    done
}

# Main script logic
if [ "$#" -eq 1 ]; then
    display_default_subdomains "$1"
elif [ "$#" -eq 2 ]; then
    display_info "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
