#!/usr/bin/env bash
# When passing the argument start:
# Starts manage_my_process/
# Creates a file containing its/ PID in /var/run/my_process.pid
# Displays manage_my_process started
# When passing the argument stop:
# Stops manage_my_process
# Deletes the file /var/run/my_process.pid
# Displays manage_my_process stopped
# When passing the argument restart
# Stops manage_my_process
# Deletes the file /var/run/my_process.pid
# Starts manage_my_process
# Creates a file containing its PID in /var/run/my_process.pid
# Displays manage_my_process restarted
# Displays Usage: manage_my_process {start|stop|restart} if any other argument or no argument is passed
if [ "$1" == "start" ]
then
    sudo ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "$1" == "stop" ]
then
    if [ -e /var/run/my_process.pid ]
    then
        PID=$(cat /var/run/my_process.pid)
        kill "$PID"
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running"
    fi
elif [ "$1" == "restart" ]
then
    if [ -e /var/run/my_process.pid ]
    then
        PID=$(cat /var/run/my_process.pid)
        kill "$PID"
        rm /var/run/my_process.pid
    fi

    sudo ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: $0 {start|stop|restart}"
    exit 1
fi
