#!/usr/bin/env bash
# This script will print the numbers 1-20 but with some exceptions:
# 4, 9, and 17 are bad luck numbers.

i=1

while [ $i -lt 21 ]
do
    echo $i
    case $i in
        "4") echo "bad luck from China";;
        "9") echo "bad luck from Japan";;
        "17") echo "bad luck from Italy";;
        esac
        (( i++ ))
done
