#!/usr/bin/env bash
# Script that prints all possible combinations of two two-digit numbers

hours=0

while [ $hours -le 12 ]
do
    echo "hour: $hours"
    minutes=1
    while [ $minutes -le 59 ]
    do
        echo " $minutes "
        (( minutes++ ))
    done
    (( hours++ ))
done
