#!/usr/bin/env bash
# Script that prints all possible combinations of two two-digit numbers
hours=0
minutes=0

while [ $hours -lt 12 ]
do
    echo "hour: $hours"
    minutes=1
    while [ $minutes -lt 60 ]
    do
        echo "$minutes"
        ((minutes++))
    done
    ((hours++))
done
