#!/usr/bin/env bash
# Update Nginx configuration to run as nginx user
sed -i 's/user\s*nginx;/user nginx;/g' /etc/nginx/nginx.conf
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
sed -i '/listen 80;/a listen 8080;' /etc/nginx/sites-available/default
pkill apache2
service nginx restart
