#!/usr/bin/env bash
# Update Nginx configuration to run as nginx user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
service nginx restart
