#!/usr/bin/env bash
# Install nginx on your web-01 server

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default

service nginx restart
